KSP-RO/ContractConfigurator

- source/ContractConfigurator/Parameter/VesselParameterGroup.cs
- source/ContractConfigurator/ParameterFactory/VesselParameterGroupFactory.cs
- source/ContractConfigurator/ScenarioModules/ContractVesselTracker.cs
Use when contract uses vessel assignment in a way where one VPG assigns the vessel and 1 or more other VPGs in the same contract consume it. This fixes the issue where when the vessel got destroyed the contract stays permalocked on a vessel that no longer even exists.
> Add `resetChildrenWhenVesselDestroyed` parameter to `VesselParameterGroup`

- source/ContractConfigurator/Parameter/ParameterDelegate.cs
This would allow us to surround HasCrew parameters with VPGs and thus avoid issues when switching vessels.
> Fix HasCrew misbehaving inside a VPG

- source/ContractConfigurator/Parameter/VesselParameter.cs
- source/ContractConfigurator/Parameter/VesselParameter/HasCrew.cs
- source/ContractConfigurator/Parameter/VesselParameter/HasCrewCapacity.cs
- source/ContractConfigurator/Parameter/VesselParameter/NoStaging.cs
- source/ContractConfigurator/Parameter/VesselParameter/PartValidation.cs
- source/ContractConfigurator/Parameter/VesselParameter/VesselNotDestroyed.cs
- source/ContractConfigurator/ScenarioModules/ContractVesselTracker.cs
Acting on joints breaking meant that every autostrut getting cycled or removed caused extreme amounts of unnecessary checks.
> Replace all OnPartJointBreak events with OnPartDeCouple+OnPartUndock

- GameData/ContractConfigurator/Localization/en-us.cfg
- GameData/ContractConfigurator/Localization/zh-cn.cfg
- source/ContractConfigurator/ContractType.cs
- source/ContractConfigurator/MissionControlUI.cs
- source/ContractConfigurator/Parameter/ContractConfiguratorParameter.cs
- source/ContractConfigurator/Parameter/KerbalDeathsCustom.cs
- source/ContractConfigurator/Parameter/ParameterDelegate.cs
- source/ContractConfigurator/Parameter/RecoverKerbalCustom.cs
- source/ContractConfigurator/Parameter/VesselParameter/HasCrew.cs
- source/ContractConfigurator/Parameter/VesselParameter/HasPassengers.cs
- source/ContractConfigurator/Parameter/VesselParameter/HasResource.cs
- source/ContractConfigurator/Parameter/VesselParameter/ReachState.cs
- source/ContractConfigurator/ParameterFactory.cs
- source/ContractConfigurator/ParameterFactory/ReachSpecificOrbitFactory.cs
- source/ContractConfigurator/ParameterFactory/VisitWaypointFactory.cs
Tries to generate every visible parameter when a contract is selected in the All tab. As a fallback if this fails, will try to use the Title field instead. Overall this approach appears to work rather well for contracts from RP-1 but no idea how usable it is for other contract packs.
By default is disabled on all contracts. To enable `supportsPreview = true` needs to be added to every individual `CONTRACT_TYPE`.
> Add preview of contract parameters to All tab

- GameData/ContractConfigurator/Localization/en-us.cfg
This is consistent with stock KSP and modded contracts used a mix of both title and sentence case
> Edit en-us localization to use sentence case

- source/ContractConfigurator/ContractConfigurator.cs
- source/ContractConfigurator/ContractConfigurator.csproj
- source/ContractConfigurator/Harmony/Kerbal.cs
- source/ContractConfigurator/Parameter/VesselParameter/HasCrew.cs
- source/ContractConfigurator/Parameter/VesselParameter/HasPassengers.cs
Various life support mods can kill crew inside parts. Previously those changes weren't picked up in vessel parameters.
> Support kerbals dying while parts themselves stay intact

- GameData/ContractConfigurator/Localization/en-us.cfg
- source/ContractConfigurator/Parameter/VesselParameter/PartValidation.cs
- source/ContractConfigurator/ParameterFactory/PartValidationFactory.cs
Change PartValidation so that all checks in a MODULE node apply to the same module (as you'd expect). Also support using `title` instead of `label` which will be the entire loc string, rather than <label> = <whatever internal value was specified>. Add special handling for isEnabled = True / False which will check pm.IsEnabled rather than look for a basefield.
Also fix a bug where MODULE alone was insufficient for PartValidation to parse, instead requiring part= or partModule= or one of the other fields.
> Fix some issues and enhance PartValidation

- source/ContractConfigurator/Parameter/VesselParameter.cs
On parameters like HasCrewCapacity this caused issues when the state was updated on other non-relevant vessels; causing the param on actually tracked vessel no longer being completable.
> Fix fake failed parameters breaking on tracked VPG vessels.

- source/ContractConfigurator/Parameter/Duration.cs
- source/ContractConfigurator/Parameter/VesselParameter.cs
- source/ContractConfigurator/Parameter/VesselParameter/OrbitParameter.cs
Turns out that Orbit parameter only runs checks on FlightGlobals.ActiveVessel which obviously is null in TS. Duration on the other hand is happy to invalidate the data for last tracked vessel as soon as any of the parameters are no longer met - including ones that are never even checked.
> Fix Duration getting reset when wrapped inside Orbit

- GameData/ContractConfigurator/Localization/en-us.cfg
cc.req.CompleteContract.cooldown aka "Must have completed contract <<1>> within the last <<2>>" is produced from .cfg like so:
```
REQUIREMENT
{
type = CompleteContract
contractType = someContract
cooldownDuration = 23
}
```
"cooldown" is pretty much the opposite of "within the last". The actual logic in the plugin is a cooldown. Curiously the negative (#cc.req.CompleteContract.cooldown.x) is correct.
> Fixed incorrect cc.req.CompleteContract.cooldown in localization

- source/ContractConfigurator/Behaviour/Expression.cs
I noticed ArgumentNullException spammed in my console, and after some investigation:
OrbitGenerator creates AlwaysTrue parameter which doesn't have an .ID
The problem line doesn't account for that. We can't skip parameters without an ID since they can't be referenced in PARAMETER_COMPLETED anyway.
> Fixed ArgumentNullException when using Expression and OrbitGenerator Behaviour together

- source/ContractConfigurator/Requirement/ContractCheckRequirement.cs
I tried to generate a sequence of contracts with DATA_EXPAND and .cfg like so:
```
CONTRACT_TYPE
{
name = ExampleContract
DATA_EXPAND
{
type = int
stage = [1, 2, 3]
}
DATA
{
type = int
prev = @/stage - 1
}
REQUIREMENT
{
name = CompleteContract
type = CompleteContract
contractType = "ExampleContract."+@/prev
}
...
```
I got a NullReferenceException. The code for parsing "contractType" doesn't account for it not being immediately evaluated.
By simply using SetValues as ParseValue's validation seems to do the trick. Using validation to set values feels kinda hacky, but is not without a precedent within the codebase, see: WaypointGenerator.cs:433 and 463
I also added MutuallyExclusive since be the logic in the code "tag" and "contractType" are mutually exclusive, but util is not used for some …
> Made usage of expressions in Contract Requirement possible

- source/ContractConfigurator/Parameter/VesselParameter/Rendezvous.cs
I noticed Rendezvous Parameter not turning incomplete when I get away from a target vessel, even though I had disableOnStateChange set to false.
After debugging for a bit: OnUpdate() gets called even on a disabled parameter, but there's actually no code path that sets the parameter back to incomplete.
I added that and also a check for .Enabled at the begining of OnUpdate() since there's isn't much point in checking the distance if the parameter can't change state.
> Fixed Rendezvous Parameter check not honoring disableOnStateChange=false

- source/ContractConfigurator/Parameter/VesselParameterGroup.cs
Looks like the line was deleted by mistake in [3a25a0344201b634cf4f79a4b028111d141633b5](https://github.com/KSP-RO/ContractConfigurator/commit/3a25a0344201b634cf4f79a4b028111d141633b5#diff-5a2a805a18a1a4dcc55c5a9d703ffe8eb53d79635cf8dcb7502edef7f2700106L436-R453). There's log line for it but no actual removal.
> Fixed vessel not getting dissassociated on contract completion

- GameData/ContractConfigurator/Localization/en-us.cfg
- GameData/ContractConfigurator/Localization/zh-cn.cfg
- source/ContractConfigurator/Parameter/VesselParameter/HasAntenna.cs
`antennaTransmit` doesn't include relay antennas which is kinda surprising, at least in-game-mechanics wise.
This could be achieved with 2 HasAntenna nodes inside an Any node, but that's very verbose for a pretty common use case. 
As for the Chinese translation: I won't pretend to know Chinese, but from what I gather `#cc.param.HasAntenna.transmit` was referring to a generic antenna which transmit antenna is not.
> Add EITHER type to HasAntenna requirement

- source/ContractConfigurator/ExpressionParser/ExpressionParser.cs
Kind of surprising that this is not supported already.
> Make it possible to parse an empty list

- source/ContractConfigurator/Behaviour/SpawnVessel.cs
Not sure how this is went unnoticed for so long, but the rotation of landed vessels created via `SpawnVessel` is completely bogus. 
With `heading`, `pitch` and `roll` set to 0 my craft was spawned on the side with a seemingly random heading.
At some point I tried to spawn a vessel with a clamp attached and it turned out to be very nice for debugging. Clamp allowed me to keep the rotation a given vessel was spawned with.
Anyway, `(0, 0, 0)` `heading`, `pitch` and `roll` before the fix:
The main problem, turns out, was the incorrect order of operations: `rotation * normal` -> `normal * rotation`. Changing that fixed the `(0, 0, 0)` case, but for non-zero it was still bogus.
The original code made a distinction between spawned part, the SPH and the VAB, and I'm not sure that's a good thing. …
> Fix rotation of spawned vessels

- source/ContractConfigurator/ExpressionParser/Parsers/Classes/ExperienceTraitParser.cs
- source/ContractConfigurator/ScenarioModules/PersistentDataStore.cs
- source/ContractConfigurator/Util/ConfigNodeUtil.cs
There was a missing null-check in `EQ`.
Other than that: `UNIQUE_DATA` was unable to handle `ExperienceTrait` at all.
> Fix a bug and add missing functionality relating to ExperienceTrait

- source/ContractConfigurator/Behaviour/WaypointGenerator.cs
- source/ContractConfigurator/ExpressionParser/Parsers/Behaviours/WaypointGeneratorParser.cs
`WaypointGenerator` with type `RANDOM_WAYPOINT_NEAR` now has new parameter `vessel` which conflicts with `nearIndex`. `vessel` is the name that gets defined in a VPG with the `define` keyword.
> Add support for generating waypoints centered on vessels

- source/ContractConfigurator/MissionControlUI.cs
- source/ContractConfigurator/TrackingStationUI.cs
This PR fix mission control layout and tracking station button that doesn't respect UI scaling setting.
Tested with UI scaling ranging from 80% to 200%.
> Fix UI scaling issue
